version: 2.1

jobs:
  install_dependencies_frontend:
    steps:
      - checkout
      - run:
          name: Install Node.js Dependencies
          command: npm install
          working_directory: Frontend

      - run:
          name: Install Angular CLI
          command: npm install -g @angular/cli
          working_directory: Frontend
