version: 2.1

orbs:
  node: circleci/node@5.1.0
  browser-tools: circleci/browser-tools@1.2.3

jobs: 
    angular-test:
      docker:
        - image: circleci/node:latest-browsers
      environment:
        NPM_CONFIG_PREFIX: "~/.npm-global"
      steps:
        - checkout
        - run:
            name: Install Angular Dependencies
            command: cd ~/project/Frontend && npm install --force
        - run: 
            name: Run Frontend Testcases
            command: cd ~/project/Frontend && npm run test -- --no-watch --no-progress --browsers=ChromeHeadless
workflows:
    Testcases:
      jobs:
        - node/run:
            pkg-manager: npm 
            resource_class: large 
            app-dir: ~/project/Backend 
            npm-run: test
            parallelism: 4

        - angular-test
  
