version: 2.1

orbs:
  node: circleci/node@5.1.0

jobs: 
    angular-test:
      docker:
        - image: circleci/node:erbium-bullseye-browsers-legacy
      environment:
        NPM_CONFIG_PREFIX: "~/.npm-global"
      steps:
        - checkout
        - run: 
            command: echo "deb http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google.list
        - run: 
            command: apt-get update
        - run: 
            command: apt-get install -y google-chrome-stable xvfb
        - run:
            name: Install Angular CLI
            command: npm install -g @angular/cli
        - run:
            name: Change folder
            command: cd ~/project/Frontend
        - run:
            name: Install Angular Dependencies
            command: cd ~/project/Frontend && npm install --force
        - run:
            name: Run Angular Tests
            command: cd ~/project/Frontend && ng test
workflows:
    backend:
      jobs:
        - node/run:
            pkg-manager: npm 
            resource_class: large 
            app-dir: ~/project/Backend 
            npm-run: test

        - angular-test
  