version: 2.1

orbs:
  node: circleci/node@5.1.0

jobs: 
    angular-test:
      docker:
        - image: circleci/node:14.17  # Use the appropriate Node.js version
      environment:
        NPM_CONFIG_PREFIX: "~/.npm-global"
      steps:
        - checkout
        - run:
            name: Install Angular CLI
            command: npm install -g @angular/cli
        - run:
            name: Install Angular Dependencies
            command: npm install
        - run:
            name: Run Angular Tests
            command: ng test
workflows:
    backend:
      jobs:
        - node/run:
            pkg-manager: npm 
            resource_class: large 
            app-dir: ~/project/Backend 
            npm-run: test

        - angular-test
  