version: 2.1

orbs:
  node: circleci/node@5.1.0
  browser-tools: circleci/browser-tools@1.2.3

jobs: 
    angular-test:
      docker:
        - image: circleci/node:latest-browsers
      environment:
        NPM_CONFIG_PREFIX: "~/.npm-global"
      steps:
        - checkout
        - run:
            name: Install Angular Dependencies
            command: cd ~/project/Frontend && npm install --force
        - run: 
            name: Run Frontend Testcases
            command: cd ~/project/Frontend && npm run test -- --no-watch --no-progress --browsers=ChromeHeadless
    
    build_and_push:
      docker:
        - image: circleci/node:latest-browsers
      steps:
        - checkout
        - setup_remote_docker:
            version: 19.03.13
        - run:
            name: Build Docker Image
            command: cd ~/project && docker build -t $DOCKERHUB_USERNAME/agricom:${CIRCLE_SHA1} .
        - run:
            name: Authenticate with Docker Hub
            command: cd ~/project && echo "$DOCKERHUB_PASS" | docker login --username $DOCKERHUB_USERNAME --password-stdin
        - run:
            name: Push Docker Image to Docker Hub
            command: cd ~/project && docker push $DOCKERHUB_USERNAME/agricom:${CIRCLE_SHA1}

workflows:
    Testcases:
      jobs:
        - node/run:
            pkg-manager: npm 
            resource_class: large 
            app-dir: ~/project/Backend 
            npm-run: test

        - angular-test
    
    build_and_deploy:
      jobs:
        - build_and_push
  
